# This is a basic workflow to help you get started with GitHub Actions 
name: Risksek react2 application dev deploy

# Triggers the workflow on push events but only for the development branch
on:
  push:
   branches: [ "develop" ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]    

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3

# Setup NodeJS in our environment
    - name: set up Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

# Runs a set of commands using the runners shell
    - run: |
           npm i
           CI=false npm run build:dev
           
# Syncs your 'build' folder from buildng the app with an S3 bucket
    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
          args: --acl private --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
      env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'build/'

# Clears the CloudFront cache so new requests will receive the latest version of your app
    - name: Invalidate Cloudfront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: '/*'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
    
# send email notifications for build status    
    - name: Send email notifications
      if: always()
      uses: dawidd6/action-send-mail@v3
      # mail server settings
      with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ${{ github.job }} job is ${{ job.status }}
          from: ${{ secrets.SMTP_FROM }}
          to: ${{ secrets.SMTP_TO }}
          body: |             
              Hello,
              This is an automated message from GitHub Actions.
                    
              Job status: ${{ job.status }} 
              Commit Message: ${{ github.event.head_commit.message }}
              Repository: ${{ github.repository }}    
          
              You can check the logs of the build here: ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}

              Regards,
              GitHub Actions
